export const images: any = {
  blurbg: require("../../assets/images/blurbg.png"),
  bgblur: require("../../assets/images/background-blur.png"),
  questionbg: require("../../assets/images/question-bg.png"),
  questionmark: require("../../assets/images/question-mark.png"),
  boule: require("../../assets/images/boule/boule.png"),
  bouleSelected: require("../../assets/images/boule/boule-selected.png"),
  bouleUnderline: require("../../assets/images/boule/boule-underline.png"),
  bgheader: require("../../assets/images/bg-header.png"),
  timeDot: require("../../assets/images/time-dot.png"),
  auth: {
    background: require("../../assets/images/auth/background.png"),
    bubble: require("../../assets/images/auth/bubble.png"),
    circle: require("../../assets/images/auth/circle.png"),
    light: require("../../assets/images/auth/light.png"),
  },
  home: {
    grand: require("../../assets/images/home/grand.png"),
    gainGrand: require("../../assets/images/gain-grand.png"),
  },
  drawer: {
    bubble: require("../../assets/images/drawer/bubble.png"),
  },
  lotteryDraw: {
    background: require("../../assets/images/lotteryDraw/background.png"),
    sun: require("../../assets/images/lotteryDraw/sun.png"),
    boole: require("../../assets/images/lotteryDraw/boole.png"),
    backgroundRST:  require("../../assets/images/lotteryDraw/backgroundRST.png"),
    bnv: require("../../assets/images/lotteryDraw/Boule_non_vérifié.png"),
    bv: require("../../assets/images/lotteryDraw/Boules_vérifié.png"),
  },
  logo: require("../../assets/images/logo.jpeg"),
  profile: require("../../assets/images/userProfile.png"),
  circleBackground: require("../../assets/images/circleBackground.png"),
  newLogo: require("../../assets/images/newLogo.png"),
  logoMini: require("../../assets/images/logo.png"),
  Menu: require("../../assets/images/Menu.png"),
  Tree: require("../../assets/images/tree.png"),
  logoFinal: require("../../assets/images/logoFinal.png"),
  bg: require("../../assets/images/BG.jpg"),
  parrainage: {
    background: require("../../assets/images/parrainage/background.png"),
    grand: require("../../assets/images/parrainage/grand.png"),
    illusion: require("../../assets/images/parrainage/illusion.png"),
    avatar: require("../../assets/images/parrainage/avatar.png"),
  },
};
